name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install clingo
        run: brew install clingo

      - name: Run tests
        run: bundle exec rspec
